In [9]:
import pandas as pd
import numpy as np

In [3]:
#importing the dataset
dataset_df=pd.read_csv('../datasets/boston.csv')

In [4]:
print(dataset_df)

     Unnamed: 0     CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  \
0             0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0
1             1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0
2             2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0
3             3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0
4             4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0
..          ...      ...   ...    ...   ...    ...    ...   ...     ...  ...
501         501  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0
502         502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0
503         503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0
504         504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0
505         505  0.04741   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0

       TAX  PTRATIO       B  LSTAT  PRICE
0    296.0     15.3  396.90   4.98   24.0
1    242.0     17.8  396.90   9.14   21.6
2    242.0     17.8  392.83   4.03   34.7
3    222.0     18.7  394.63   2.94   33.4
4    222.0     18.7  396.90   5.33   36.2
..     ...      ...     ...    ...    ...
501  273.0     21.0  391.99   9.67   22.4
502  273.0     21.0  396.90   9.08   20.6
503  273.0     21.0  396.90   5.64   23.9
504  273.0     21.0  393.45   6.48   22.0
505  273.0     21.0  396.90   7.88   11.9

[506 rows x 15 columns]

In [5]:
#type checking
type(dataset_df)

pandas.core.frame.DataFrame

In [6]:
dataset_df.head()

,Unnamed: 0,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,PRICE
0,0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98,24.0
1,1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14,21.6
2,2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2.0,242.0,17.8,392.83,4.03,34.7
3,3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3.0,222.0,18.7,394.63,2.94,33.4
4,4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3.0,222.0,18.7,396.90,5.33,36.2

In [7]:
dataset_df.to_csv("california_housing")

In [24]:
#xls
#data_df.to_csv("dataset name")

In [25]:
#xls
#dataset=pd.read_xls("path")

In [27]:
#creating the dataframe with random values

In [10]:
random_df=pd.DataFrame(np.random.rand(20,30))

In [11]:
random_df.head()

,0,1,2,3,4,5,6,7,8,9,...,20,21,22,23,24,25,26,27,28,29
0,0.711966,0.614167,0.605748,0.558379,0.320974,0.436336,0.151838,0.668980,0.247669,0.800093,...,0.254103,0.865189,0.908667,0.368495,0.925113,0.241924,0.299054,0.982408,0.117340,0.645275
1,0.614941,0.120135,0.413801,0.750189,0.182534,0.744033,0.708796,0.360563,0.625767,0.881015,...,0.134016,0.349041,0.317496,0.103726,0.264896,0.039634,0.840733,0.031780,0.208142,0.614693
2,0.394805,0.242282,0.806936,0.120924,0.228803,0.274217,0.969081,0.072590,0.639064,0.200487,...,0.760816,0.832297,0.649192,0.364923,0.325963,0.986244,0.476768,0.979545,0.901598,0.943559
3,0.561157,0.700949,0.131020,0.702913,0.902099,0.306149,0.509173,0.906060,0.955400,0.450424,...,0.813571,0.998704,0.693209,0.647177,0.519324,0.691386,0.515789,0.661860,0.977737,0.000565
4,0.815530,0.811355,0.800210,0.319766,0.574031,0.926764,0.164644,0.546780,0.710953,0.238371,...,0.323449,0.038711,0.526303,0.275692,0.908179,0.069882,0.336717,0.657576,0.324242,0.004492

In [30]:
random_df.shape

(20, 30)

In [12]:
#information about the dataframe
random_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 30 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       20 non-null     float64
 1   1       20 non-null     float64
 2   2       20 non-null     float64
 3   3       20 non-null     float64
 4   4       20 non-null     float64
 5   5       20 non-null     float64
 6   6       20 non-null     float64
 7   7       20 non-null     float64
 8   8       20 non-null     float64
 9   9       20 non-null     float64
 10  10      20 non-null     float64
 11  11      20 non-null     float64
 12  12      20 non-null     float64
 13  13      20 non-null     float64
 14  14      20 non-null     float64
 15  15      20 non-null     float64
 16  16      20 non-null     float64
 17  17      20 non-null     float64
 18  18      20 non-null     float64
 19  19      20 non-null     float64
 20  20      20 non-null     float64
 21  21      20 non-null     float64
 22  22      20 non-null     float64
 23  23      20 non-null     float64
 24  24      20 non-null     float64
 25  25      20 non-null     float64
 26  26      20 non-null     float64
 27  27      20 non-null     float64
 28  28      20 non-null     float64
 29  29      20 non-null     float64
dtypes: float64(30)
memory usage: 4.8 KB

In [13]:
#finding the missing values in the dataframe
random_df.isnull().sum()

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    0
17    0
18    0
19    0
20    0
21    0
22    0
23    0
24    0
25    0
26    0
27    0
28    0
29    0
dtype: int64

In [33]:
dataset_df.isnull().sum()

Unnamed: 0    0
CRIM          0
ZN            0
INDUS         0
CHAS          0
NOX           0
RM            0
AGE           0
DIS           0
RAD           0
TAX           0
PTRATIO       0
B             0
LSTAT         0
PRICE         0
dtype: int64

In [34]:
#performing the statsitcial operations on the dataframe

In [15]:
data=pd.read_csv('../datasets/diabetes.xls')

In [16]:
data.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [17]:
data.shape

(768, 9)

In [18]:
#mean of the price column
data.groupby('Outcome').mean()
#values count 
data.value_counts('Age')

Age
22    72
21    63
25    48
24    46
23    38
28    35
26    33
27    32
29    29
31    24
41    22
30    21
37    19
42    18
33    17
32    16
38    16
36    16
45    15
34    14
46    13
43    13
40    13
39    12
35    10
44     8
51     8
50     8
52     8
58     7
54     6
47     6
49     5
53     5
57     5
48     5
60     5
55     4
63     4
62     4
66     4
56     3
65     3
59     3
67     3
61     2
69     2
64     1
68     1
70     1
72     1
81     1
Name: count, dtype: int64

In [53]:
#counting the values of dataframe
data.count()

Pregnancies                 768
Glucose                     768
BloodPressure               768
SkinThickness               768
Insulin                     768
BMI                         768
DiabetesPedigreeFunction    768
Age                         768
Outcome                     768
dtype: int64

In [52]:
#mean of the column
data.mean()

Pregnancies                   3.845052
Glucose                     120.894531
BloodPressure                69.105469
SkinThickness                20.536458
Insulin                      79.799479
BMI                          31.992578
DiabetesPedigreeFunction      0.471876
Age                          33.240885
Outcome                       0.348958
dtype: float64

In [54]:
#standrd devation 
data.std()

Pregnancies                   3.369578
Glucose                      31.972618
BloodPressure                19.355807
SkinThickness                15.952218
Insulin                     115.244002
BMI                           7.884160
DiabetesPedigreeFunction      0.331329
Age                          11.760232
Outcome                       0.476951
dtype: float64

In [55]:
#minimun values in each column
data.min()

Pregnancies                  0.000
Glucose                      0.000
BloodPressure                0.000
SkinThickness                0.000
Insulin                      0.000
BMI                          0.000
DiabetesPedigreeFunction     0.078
Age                         21.000
Outcome                      0.000
dtype: float64

In [56]:
#for maximum
data.max()

Pregnancies                  17.00
Glucose                     199.00
BloodPressure               122.00
SkinThickness                99.00
Insulin                     846.00
BMI                          67.10
DiabetesPedigreeFunction      2.42
Age                          81.00
Outcome                       1.00
dtype: float64

In [57]:
#all in one function
data.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000