In [2]:
import pandas as pd
import numpy as np

In [4]:
dataset = pd.read_csv('../datasets/boston.csv')
print(dataset)

     Unnamed: 0     CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  \
0             0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0
1             1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0
2             2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0
3             3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0
4             4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0
..          ...      ...   ...    ...   ...    ...    ...   ...     ...  ...
501         501  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0
502         502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0
503         503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0
504         504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0
505         505  0.04741   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0

       TAX  PTRATIO       B  LSTAT  PRICE
0    296.0     15.3  396.90   4.98   24.0
1    242.0     17.8  396.90   9.14   21.6
2    242.0     17.8  392.83   4.03   34.7
3    222.0     18.7  394.63   2.94   33.4
4    222.0     18.7  396.90   5.33   36.2
..     ...      ...     ...    ...    ...
501  273.0     21.0  391.99   9.67   22.4
502  273.0     21.0  396.90   9.08   20.6
503  273.0     21.0  396.90   5.64   23.9
504  273.0     21.0  393.45   6.48   22.0
505  273.0     21.0  396.90   7.88   11.9

[506 rows x 15 columns]

In [5]:
dataset.head()

,Unnamed: 0,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,PRICE
0,0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98,24.0
1,1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14,21.6
2,2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2.0,242.0,17.8,392.83,4.03,34.7
3,3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3.0,222.0,18.7,394.63,2.94,33.4
4,4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3.0,222.0,18.7,396.90,5.33,36.2

In [7]:
type(dataset)

pandas.core.frame.DataFrame

In [10]:
random_ds = pd.DataFrame(np.random.rand(10,5))
random_ds.head()

          0         1         2         3         4
0  0.346211  0.759165  0.479139  0.730112  0.853441
1  0.801711  0.473022  0.317619  0.396558  0.742190
2  0.031023  0.146418  0.965103  0.588687  0.363399
3  0.837262  0.316198  0.601439  0.798286  0.823115
4  0.099542  0.579663  0.042031  0.040355  0.420135

In [11]:
random_ds.tail()

          0         1         2         3         4
5  0.239684  0.146828  0.979678  0.328600  0.932586
6  0.708812  0.409066  0.555552  0.879307  0.095673
7  0.585505  0.206526  0.595271  0.168137  0.181645
8  0.384078  0.920245  0.862203  0.596358  0.838131
9  0.649629  0.874309  0.530206  0.970881  0.195068

In [13]:
random_ds.shape
random_ds.info

<bound method DataFrame.info of           0         1         2         3         4
0  0.346211  0.759165  0.479139  0.730112  0.853441
1  0.801711  0.473022  0.317619  0.396558  0.742190
2  0.031023  0.146418  0.965103  0.588687  0.363399
3  0.837262  0.316198  0.601439  0.798286  0.823115
4  0.099542  0.579663  0.042031  0.040355  0.420135
5  0.239684  0.146828  0.979678  0.328600  0.932586
6  0.708812  0.409066  0.555552  0.879307  0.095673
7  0.585505  0.206526  0.595271  0.168137  0.181645
8  0.384078  0.920245  0.862203  0.596358  0.838131
9  0.649629  0.874309  0.530206  0.970881  0.195068>

In [15]:
random_ds.isnull().sum()

0    0
1    0
2    0
3    0
4    0
dtype: int64

In [17]:
dataset2 = pd.read_csv('../datasets/diabetes.xls')

In [19]:
print(dataset2)

     Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6
1              1       85             66             29        0  26.6
2              8      183             64              0        0  23.3
3              1       89             66             23       94  28.1
4              0      137             40             35      168  43.1
..           ...      ...            ...            ...      ...   ...
763           10      101             76             48      180  32.9
764            2      122             70             27        0  36.8
765            5      121             72             23      112  26.2
766            1      126             60              0        0  30.1
767            1       93             70             31        0  30.4

     DiabetesPedigreeFunction  Age  Outcome
0                       0.627   50        1
1                       0.351   31        0
2                       0.672   32        1
3                       0.167   21        0
4                       2.288   33        1
..                        ...  ...      ...
763                     0.171   63        0
764                     0.340   27        0
765                     0.245   30        0
766                     0.349   47        1
767                     0.315   23        0

[768 rows x 9 columns]

In [20]:
dataset2.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [24]:
dataset2.groupby('Outcome').mean()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
Outcome,,,,,,,,
0,3.298000,109.980000,68.184000,19.664000,68.792000,30.304200,0.429734,31.190000
1,4.865672,141.257463,70.824627,22.164179,100.335821,35.142537,0.550500,37.067164

In [28]:
dataset2.value_counts('Pregnancies')

Pregnancies
1     135
0     111
2     103
3      75
4      68
5      57
6      50
7      45
8      38
9      28
10     24
11     11
13     10
12      9
14      2
15      1
17      1
Name: count, dtype: int64

In [29]:
dataset2.count()

Pregnancies                 768
Glucose                     768
BloodPressure               768
SkinThickness               768
Insulin                     768
BMI                         768
DiabetesPedigreeFunction    768
Age                         768
Outcome                     768
dtype: int64

In [30]:
dataset2.mean()

Pregnancies                   3.845052
Glucose                     120.894531
BloodPressure                69.105469
SkinThickness                20.536458
Insulin                      79.799479
BMI                          31.992578
DiabetesPedigreeFunction      0.471876
Age                          33.240885
Outcome                       0.348958
dtype: float64

In [32]:
dataset.describe()

,Unnamed: 0,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,PRICE
count,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000
mean,252.500000,3.613524,11.363636,11.136779,0.069170,0.554695,6.284634,68.574901,3.795043,9.549407,408.237154,18.455534,356.674032,12.653063,22.532806
std,146.213884,8.601545,23.322453,6.860353,0.253994,0.115878,0.702617,28.148861,2.105710,8.707259,168.537116,2.164946,91.294864,7.141062,9.197104
min,0.000000,0.006320,0.000000,0.460000,0.000000,0.385000,3.561000,2.900000,1.129600,1.000000,187.000000,12.600000,0.320000,1.730000,5.000000
25%,126.250000,0.082045,0.000000,5.190000,0.000000,0.449000,5.885500,45.025000,2.100175,4.000000,279.000000,17.400000,375.377500,6.950000,17.025000
50%,252.500000,0.256510,0.000000,9.690000,0.000000,0.538000,6.208500,77.500000,3.207450,5.000000,330.000000,19.050000,391.440000,11.360000,21.200000
75%,378.750000,3.677083,12.500000,18.100000,0.000000,0.624000,6.623500,94.075000,5.188425,24.000000,666.000000,20.200000,396.225000,16.955000,25.000000
max,505.000000,88.976200,100.000000,27.740000,1.000000,0.871000,8.780000,100.000000,12.126500,24.000000,711.000000,22.000000,396.900000,37.970000,50.000000

In [34]:
data3 = pd.read_csv('../datasets/Placement_Dataset.csv')
print(data3)

     sl_no gender  ssc_p    ssc_b  hsc_p    hsc_b     hsc_s  degree_p  \
0        1      M  67.00   Others  91.00   Others  Commerce     58.00
1        2      M  79.33  Central  78.33   Others   Science     77.48
2        3      M  65.00  Central  68.00  Central      Arts     64.00
3        4      M  56.00  Central  52.00  Central   Science     52.00
4        5      M  85.80  Central  73.60  Central  Commerce     73.30
..     ...    ...    ...      ...    ...      ...       ...       ...
210    211      M  80.60   Others  82.00   Others  Commerce     77.60
211    212      M  58.00   Others  60.00   Others   Science     72.00
212    213      M  67.00   Others  67.00   Others  Commerce     73.00
213    214      F  74.00   Others  66.00   Others  Commerce     58.00
214    215      M  62.00  Central  58.00   Others   Science     53.00

      degree_t workex  etest_p specialisation  mba_p      status    salary
0     Sci&Tech     No     55.0         Mkt&HR  58.80      Placed  270000.0
1     Sci&Tech    Yes     86.5        Mkt&Fin  66.28      Placed  200000.0
2    Comm&Mgmt     No     75.0        Mkt&Fin  57.80      Placed  250000.0
3     Sci&Tech     No     66.0         Mkt&HR  59.43  Not Placed       NaN
4    Comm&Mgmt     No     96.8        Mkt&Fin  55.50      Placed  425000.0
..         ...    ...      ...            ...    ...         ...       ...
210  Comm&Mgmt     No     91.0        Mkt&Fin  74.49      Placed  400000.0
211   Sci&Tech     No     74.0        Mkt&Fin  53.62      Placed  275000.0
212  Comm&Mgmt    Yes     59.0        Mkt&Fin  69.72      Placed  295000.0
213  Comm&Mgmt     No     70.0         Mkt&HR  60.23      Placed  204000.0
214  Comm&Mgmt     No     89.0         Mkt&HR  60.22  Not Placed       NaN

[215 rows x 15 columns]

In [35]:
data3.head()

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
0,1,M,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed,270000.0
1,2,M,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed,200000.0
2,3,M,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,Placed,250000.0
3,4,M,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.0,Mkt&HR,59.43,Not Placed,NaN
4,5,M,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.8,Mkt&Fin,55.50,Placed,425000.0

In [43]:
#data3.groupby('hsc_p').mean()
data3.value_counts('gender')

gender
M    139
F     76
Name: count, dtype: int64

In [42]:
data3.value_counts('workex')

workex
No     141
Yes     74
Name: count, dtype: int64

In [44]:
data3.value_counts('specialisation')

specialisation
Mkt&Fin    120
Mkt&HR      95
Name: count, dtype: int64

In [45]:
data3.value_counts('status')

status
Placed        148
Not Placed     67
Name: count, dtype: int64

In [47]:
data3.count()

sl_no             215
gender            215
ssc_p             215
ssc_b             215
hsc_p             215
hsc_b             215
hsc_s             215
degree_p          215
degree_t          215
workex            215
etest_p           215
specialisation    215
mba_p             215
status            215
salary            148
dtype: int64

In [50]:
data3.describe()

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary
count,215.000000,215.000000,215.000000,215.000000,215.000000,215.000000,148.000000
mean,108.000000,67.303395,66.333163,66.370186,72.100558,62.278186,288655.405405
std,62.209324,10.827205,10.897509,7.358743,13.275956,5.833385,93457.452420
min,1.000000,40.890000,37.000000,50.000000,50.000000,51.210000,200000.000000
25%,54.500000,60.600000,60.900000,61.000000,60.000000,57.945000,240000.000000
50%,108.000000,67.000000,65.000000,66.000000,71.000000,62.000000,265000.000000
75%,161.500000,75.700000,73.000000,72.000000,83.500000,66.255000,300000.000000
max,215.000000,89.400000,97.700000,91.000000,98.000000,77.890000,940000.000000